
CREATE TABLE PARENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    CHILD INTEGER,
    CONSTRAINT u_pub_doubles UNIQUE (NAME, LAST_NAME)
);

CREATE TABLE CHILD (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  PARENT INTEGER NOT NULL,
  FOREIGN KEY (PARENT) REFERENCES PARENT(ID)
);

CREATE TABLE GRANDCHILD (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  CHILD INTEGER NOT NULL,
  FOREIGN KEY (CHILD) REFERENCES CHILD(ID)
);
